language: ruby
bundler_args: --without development non_travis
rvm:
  - 1.9.3
before_script:
  - "rake db:create"
  - "rake db:migrate"
branches:
  only:
    - master
notifications:
  campfire: railslovehq:ef17dd0832a81839be6015cefdaf3ecc08316ccb@350507
  on_success: change
  on_failure: always
